### ISSUE TITLE
Authorization header not being sent in request

### ISSUE THREAD

**Issue by heinickk** [sureshchahal/angular2-adal#12]
When implementing the NG2-Adal package, I am not seeing the authorization token being  sent in the request. We see the auth token being saved to local storage, so the initial authentication from Azure seems to be correct. Any suggestions on how to figure out the issue would be appreciated.

**Comment by MikeLallemont** [comment]
I am having the same issue. We need some kind of example or basic information on how this works.

**Comment by sureshchahal** [comment]
Are you using authhttp class provided in package. That take care of sending
token

**Comment by heinickk** [comment]
We are also noticing that the returned token is causing a routing issue where it can't direct to id_token. The  location comes back as /#id_token=. We are implementing the Ang 2.0 Router witht the HashLocationStrategy within our boot  module.

**Comment by heinickk** [comment]
Yes. We discovered the AuthHttp service and using that for the Http calls seems to fix the token issue not being in the request. Thanks for the quick response.

**Comment by sureshchahal** [comment]
Great can you close this issue?
