### ISSUE TITLE
URL query params are double encoded.

### ISSUE THREAD

**Issue by harry671003** [sureshchahal/angular2-adal#19]
When passed a query string that contains special characters, eg: { , the url is being encoded twice.

```ts
let filter = {
    Field: 'Name',
    Value: 'Alex',
    Operator: 'Equals'
};

let searchParams: URLSearchParams = new URLSearchParams();
searchParams.set('filter', JSON.stringify(filter));

this.authHttp.get(
    apiUrl,
    new RequestOptions({
        headers: additionalHeaders,
        search: searchParams
    })
);
```

The query string is `filter= {Field: 'Name', Value: 'Alex', Operator: 'Equals'}`

Here `{` becomes `%7B`, before being passed to `authHttp.get` and inside `sendRequest` the `%` will again be encoded to `%25` resulting in `%257B`

**Comment by sureshchahal** [comment]
@harry671003 Just fixed this and uploaded again. Can you please verify?

**Comment by harry671003** [comment]
@sureshchahal Just verified this. This works perfectly. Thanks!
