### ISSUE TITLE
npm package ng2-adal 0.2.7 is out of sync with github src and re-introduced the require for 'adal' alias in Webpack

### ISSUE THREAD

**Issue by nelsonmorais** [sureshchahal/angular2-adal#20]
Hi Suresh,

Last Friday you've pushed a new package to NPM with version 0.2.7 that is out of sync with what we see in Github, which is version 0.2.6.

On that package you also re-introduced the need to have an alias in Webpack for 'adal' because the file https://github.com/sureshchahal/angular2-adal/blob/master/src/services/adal.service.ts has again the following code:
import adalLib = require('adal');

instead of from version 0.2.6:
import * as adalLib from 'adal-angular';

Can you have this fixed?
Many thanks!

**Comment by sureshchahal** [comment]
@nelsonmorais  thanks for catching this. I have fixed the issue and  published it again with version 0.2.8

**Comment by nelsonmorais** [comment]
Thanks! It's working now ;)
