### ISSUE TITLE
errors during acquireToken are not bubbling up

### ISSUE THREAD

**Issue by cbrianball** [sureshchahal/angular2-adal#26]
The main issue looks to be the call (within adal.service.js) to `acquireToken`. If there's an error, it calls `this.adalContext.error`, but `this` isn't referring to the current class since it's not being called inside a rocket function (=>).

Also, I'm very new to rxjs, but I don't believe the code, as it stands in `acquireToken`, will cause an error to be raised by the Observable if there is an error,, it will simply return a `null` value for the token, is this by design?

**Comment by cbrianball** [comment]
Sorry for the poor job of explaining what the issue is. So I decided to go ahead and make a PR, hopefully that (along with my commit message), will make the issue easier to understand.

**Comment by lutzleonhardt** [comment]
I have the same observation in my code, errors in aquireToken does not call the Observable catch function:

```
return this.authhttp.request(url_, {
            body: content_,
            method: 'get',
            headers: new Headers({
                'Ocp-Apim-Subscription-Key': ocp_Apim_Subscription_Key,
                'Content-Type': 'application/json; charset=UTF-8'
            })
        }).map((response) => {
           ...
        }).catch((response: any, caught: any) => {
           ...
        });
```

When will this be merged?

**Comment by DaimlerVan** [comment]
The 2nd parameter of Observable.bindCallback() have to be a selector function when specified to return the emited value (which is used when you subscribe to the generated observable).

In this case the function

```
function(token: string){
 +            if(!token && errorMessage)
 +                throw(errorMessage);
          }
```

does not return the token. So for me this fix is not working.

**Comment by DaimlerVan** [comment]
this should fix it:
https://github.com/DaimlerVan/angular2-adal/commit/071f0a5e583f41c5f6968d53bdb77de4874fa03c

**Comment by cbrianball** [comment]
Thanks Daimler, this was the first time I worked with observable, I only tested the error path.
