### ISSUE TITLE
You can find a sample app that uses popUp here

### ISSUE THREAD

**Issue by mazhisai** [sureshchahal/angular2-adal#34]
i have extended the sample app as an example for popUp @ https://github.com/mazhisai/ng2-adal-QuickStart. please check it out and let me know your comments.

**Comment by mazhisai** [comment]
I am having issues getting it to work on Edge. works fine on chrome and firefox. if you guys have any thoughts/inputs, please share.

**Comment by mazhisai** [comment]
Edge issue possibly related to this https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/457

**Comment by sureshchahal** [comment]
Sample app link included in documentation. @mazhisai should we close this issue now

**Comment by mazhisai** [comment]
Thanks @sureshchahal, closing it.
