### ISSUE TITLE
@Types vs Typings

### ISSUE THREAD

**Issue by Highspeed7** [sureshchahal/angular2-adal#4]
This project has a dependency on Typescript 2.0.6 which now uses @Types and not Typings. Would be beneficial to no longer rely on Typings.

**Comment by sureshchahal** [comment]
@Highspeed7 : thank you I will read about @Types and try to update.

**Comment by DarkXaHTeP** [comment]
Hi, @sureshchahal. I'm ready to convert library to use @types. Also I may help with converting it to Webpack instead of gulp and setup Travis CI. Let me know if you're interested

**Comment by sureshchahal** [comment]
@DarkXaHTeP : Sure I am in for converting it to use @Types.

For converting it to use webpack instead of gulp,  have no open request so a bit concerned if other are using gulp. Let's get a vote on this

**Comment by DarkXaHTeP** [comment]
@sureshchahal it will not change a way library is used. Just make development a bit easier

**Comment by DarkXaHTeP** [comment]
@sureshchahal, @Highspeed7 I guess this issue can be closed now, after #18 is merged and published to npm. What do you think?
