### ISSUE TITLE
Observable.thow is not a function

### ISSUE THREAD

**Issue by isaacrlevin** [sureshchahal/angular2-adal#40]
I get this error in the handle error handler

> Error: Uncaught (in promise): TypeError: a.Observable.throw is not a function TypeError: a.Observable.throw is not a function     at AuthHttp.sendRequest ()

According to this issue in rxjs, there is a context issue that can easily be resolved

https://github.com/ReactiveX/rxjs/issues/1866

Here you just need an include for 
import 'rxjs/add/observable/throw';

And this bug goes away. I can create a PR or you can just add it if you like.

**Comment by sureshchahal** [comment]
thanks @isaac2004. Can you please create a PR?

**Comment by isaacrlevin** [comment]
@sureshchahal Done!
https://github.com/sureshchahal/angular2-adal/pull/41

**Comment by abdel-ships-it** [comment]
I have a strange feeling `import 'rxjs/add/observable/throw'` won't solve the problem as my typescript compiler still cannot find throw even if its imported.

Just a heads up but I think your`throw.d.ts` under `rxjs/add/observable/` is empty.

**Comment by sureshchahal** [comment]
This issue is fixed as i have reverted change to import just Observable. Still looking for ways to reduce size

**Comment by rjwijnen** [comment]
Please reopen this issue. With 1.0.1 i got this error again: ERROR TypeError: Observable_1.Observable.throw is not a function
    at AuthHttp.webpackJsonp../node_modules/ng2-adal/services/authHttp.service.js.AuthHttp.sendRequest

**Comment by isaacrlevin** [comment]
@rjwijnen are you using the latest version?

**Comment by rjwijnen** [comment]
Yes, i am using the latest version. Can someone put the import 'rxjs/add/observable/throw'; back in the authHttp.service?

**Comment by isaacrlevin** [comment]
@realappie @sureshchahal did we test that my PR wasn't needed? I still think it is per issues addressed

**Comment by sureshchahal** [comment]
I don't get any observable error during build. I will check later today.

**Comment by isaacrlevin** [comment]
@sureshchahal try to stub out calling an api that returns a 500. That is how I tested

**Comment by rjwijnen** [comment]
Have you test this again @sureshchahal ?
