### ISSUE TITLE
Cannot find namespace 'adal'

### ISSUE THREAD

**Issue by isaacrlevin** [sureshchahal/angular2-adal#5]
When referencing this module from npm, you get this error in 2 locations

node_modules/ng2-adal/ts/services/ada.service.ts
node_modules/ng2-adal/services/ada.service.d.ts

Seems to be that the typings are not being resolved properly. Adding this code in both of those files fixes the issue

`///<reference path="./../adal/index.d.ts"/>`

This is a temp fix obviously, but fixes the issue and auth is working fine

**Comment by bhosale-ajay** [comment]
Add that reference to main.ts (or entry point of your application) instead of adding to ada.service.ts

**Comment by MikeLallemont** [comment]
This works in Ionic but I had to remove @types/adal package which works fine on a Mac but not on Windows. 

We need this to be fixed correctly in the ng2-adal package so we don't need this work around. 

Thanks for creating this package though, it is much needed.
